# Numpy array creation

In [1]:
import numpy as np

# arange

In [2]:
np.arange(6)
# starts from 0 and stop at num-1

array([0, 1, 2, 3, 4, 5])

In [3]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.arange(1,10,2)  #stepping

array([1, 3, 5, 7, 9])

# Zeros(): Array with all zeros

In [5]:
"""
eros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.
"""
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
#2D array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#3D array
np.zeros((3,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [11]:
# if i want int zero then
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [12]:
np.zeros((4,2,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

# ones():array with all ones

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.ones((3,2,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# Empty(): array with all empty

In [17]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.empty((3,2,3),dtype=int)

array([[[   0,    0,    0],
        [   0,    0,    0]],

       [[   0,    0,    0],
        [   0, 1456,    0]],

       [[   0,    0,    0],
        [   0,    0,    0]]])

In [19]:
np.empty((4,5),dtype=str)

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [20]:
np.empty((3,4,5))

array([[[1.49379171e-311, 1.49378067e-311, 3.60960968e-310,
         5.79100229e-085, 1.00678753e-312],
        [1.31353237e-308, 1.33360294e+241, 1.12253577e-311,
         2.75909158e-306, 4.03347591e-270],
        [6.22993169e-222, 3.20004826e-241, 1.10266576e-279,
         2.18254133e-289, 2.18254133e-289],
        [3.20443318e-241, 2.18354343e-289, 5.60174664e-275,
         7.43703987e-251, 1.08742203e-202]],

       [[6.93235115e-222, 5.08162500e-299, 5.89225648e-222,
         1.83795625e-260, 7.45749275e-251],
        [4.03162756e-270, 7.45749286e-251, 7.43704018e-251,
         1.54109650e-231, 2.31130530e-289],
        [1.72839821e-260, 1.08692755e-202, 1.72839821e-260,
         4.61249233e-303, 9.98110230e-110],
        [9.73358883e-207, 3.18093783e+151, 1.26927730e-277,
         1.89120668e+219, 3.44999157e-085]],

       [[2.64685961e+180, 5.30733197e-201, 6.74111711e+199,
         7.98578458e+151, 4.62232807e-292],
        [1.10262801e+161, 6.21823822e-311, 3.42196482e-210,


In [21]:
np.empty((3,4,5),dtype=int)

array([[[-263099912,        703,        205,          0,          0],
        [         0,          0,          0,          0,    4259932],
        [1633952379,  975332724,  808591904,  825045554,  942681394],
        [ 976826452,  876228658,  909585969,  808464439,  539763290]],

       [[1735617826,  577005919,  807542842,  892953907,  929183029],
        [ 876099941,  943077473,  895575607,  959918899,  845557862],
        [ 573714787, 1965170732, 1852990835,  577072481, 1965170746],
        [1852990835,  577072481, 1931616300, 1769173861,  975335023]],

       [[1664688672, 1650550323, 1667523683,  808728118, 1698194530],
        [1684090977,  875848761, 1647851874,  740451895, 1936532000],
        [2037669735,  975332720, 2019893792, 1953850213, 1701994341],
        [1936029041,  539763316, 1919252002, 1852795251,  572537378]]])

# full(): supply own value in arrray

In [22]:
#Signature: np.full(shape, fill_value, dtype=None, order='C', *, like=None)
#Docstring:
#Return a new array of given shape and type, filled with `fill_value`.

np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [24]:
np.full((4,5),200)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])

In [25]:
np.full(13,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [28]:
np.full((4,4),fill_value='Null')

array([['Null', 'Null', 'Null', 'Null'],
       ['Null', 'Null', 'Null', 'Null'],
       ['Null', 'Null', 'Null', 'Null'],
       ['Null', 'Null', 'Null', 'Null']], dtype='<U4')

# empty():array with garbage values

In [29]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [30]:
np.empty((5),dtype=int)

array([-212934576,        703,          0,          0,     131074])

In [31]:
np.empty((4,5),dtype=int)

array([[-1, -1,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [32]:
np.empty((4,4,4),dtype=int)

array([[[-208006488,        703,        216,          0],
        [         0,          0,          0,          0],
        [         0,          0, 1936532091, 1684627303],
        [ 572537378,  892363319,  929117029,  929444653]],

       [[ 842293808,  929181797, 1714762081,  842412854],
        [1630876724,  959536995, 1597257269,  573714737],
        [1830953004, 1952409459,  577073273, 1696735290],
        [1969448312, 1918854516, 1819636581,  539763316]],

       [[1702065442, 1835101810,  540680805, 1702065442],
        [1835101810,  539763301, 1936028450, 1852795251],
        [ 572537378,  892363319,  929117029,  929444653],
        [ 842293808,  929181797, 1714762081,  842412854]],

       [[1630876724,  539763299, 1952539682,  540680805],
        [ 842019362,  842083634, 1412968493,  842676528],
        [ 808466992,  825373742, 1513369649,  572533794],
        [1936876918,  577662825,  891428922, 2099393326]]])

### identity(): identity matrix
...diagonal elements 1 and non diagonal 0

In [33]:
# n: means N x N array
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.identity(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [36]:
np.identity((3,3),dtype=int)

TypeError: 'tuple' object cannot be interpreted as an integer

# eye(): used to crreate an identity matrix

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
#np.identity(n, dtype=None, *, like=None)
#np.eye(N, M=None, k=0, dtype=<class 'float'>)
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [42]:
np.eye(5,5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.eye(4,6,k=4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [44]:
np.eye(3,3,k=2,dtype=int)

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

### linspace(): array with linearly spaced values

In [45]:
"""
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
"""
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [48]:
np.linspace(2,10,retstep=True)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 0.16326530612244897)

In [49]:
np.linspace(3,10,num=20,endpoint=False,retstep=True)

(array([3.  , 3.35, 3.7 , 4.05, 4.4 , 4.75, 5.1 , 5.45, 5.8 , 6.15, 6.5 ,
        6.85, 7.2 , 7.55, 7.9 , 8.25, 8.6 , 8.95, 9.3 , 9.65]),
 0.35)

In [50]:
x=np.identity(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.diagonal(x)##gives u an access to diagonal elements

array([1., 1., 1., 1., 1.])

# random(): creates a random number


In [52]:
#random(size=None)
#Return random floats in the half-open interval [0.0, 1.0).
np.random.random(6)

array([0.08926435, 0.00676581, 0.86518639, 0.59004281, 0.39867831,
       0.23145071])

In [53]:
np.random.random((2,3))

array([[0.88962691, 0.45266092, 0.02375906],
       [0.21313409, 0.9980215 , 0.0924522 ]])

In [54]:
np.random.random((3,4,5))

array([[[0.20706599, 0.90269372, 0.63749495, 0.86098644, 0.18900875],
        [0.45219272, 0.93924345, 0.87246265, 0.73749088, 0.24934629],
        [0.39449398, 0.58454573, 0.73483812, 0.05671854, 0.56360754],
        [0.52085873, 0.00207751, 0.47754131, 0.98552772, 0.27925166]],

       [[0.40683321, 0.61086352, 0.19506486, 0.39486077, 0.12009846],
        [0.21039711, 0.86780879, 0.00371116, 0.09591738, 0.98977353],
        [0.78270968, 0.7961786 , 0.47598746, 0.13433944, 0.08976424],
        [0.60854175, 0.57105185, 0.51347089, 0.07806232, 0.94167319]],

       [[0.61114738, 0.39756469, 0.15503126, 0.51842393, 0.34192854],
        [0.05017795, 0.29407988, 0.70500562, 0.79504795, 0.33721165],
        [0.1099043 , 0.3132952 , 0.53016687, 0.46660361, 0.97038749],
        [0.5158931 , 0.87394702, 0.17293235, 0.16794233, 0.32481866]]])

In [55]:
# random int values
#randint(low, high=None, size=None, dtype=int)
np.random.randint(8,size=20) # when we supply only low then it is exclusive

array([0, 0, 1, 0, 2, 3, 7, 6, 7, 7, 5, 1, 1, 6, 0, 4, 7, 1, 1, 2])

In [56]:
# when we supply both, low and high
#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(8,20,size=20)

array([18, 18, 15, 13, 15,  9, 11, 17, 12, 13, 16, 14,  9,  8,  8, 19, 19,
       10, 15, 14])

In [57]:
# generate a data of bloodpressure in range 70-120
np.random.randint(70,121,size=50)

array([107,  96,  70, 108,  76,  75,  98,  76,  77, 110,  77,  80,  83,
        99,  95,  72,  89,  85, 105,  88, 116, 100, 105,  97, 114,  98,
       117, 116, 100, 109,  87,  84,  85,  95,  71, 100,  87,  97,  76,
        96, 108, 104, 104,  78, 102,  97, 113,  91,  81, 112])

In [58]:
# salary data: 20000,60000 for 100 employees
np.random.randint(20000,60001,100)

array([27687, 38900, 55989, 28403, 47473, 47184, 56872, 32259, 20880,
       55998, 45602, 32335, 42770, 39179, 48341, 24429, 30879, 27508,
       56184, 27406, 21044, 52399, 50197, 39267, 37461, 26392, 20178,
       48786, 23274, 22237, 22233, 22774, 20198, 58271, 46853, 35630,
       26053, 33838, 51543, 45743, 23367, 50335, 55092, 58408, 24110,
       28263, 44489, 38004, 24446, 39150, 54665, 53003, 53087, 27797,
       47107, 32228, 50930, 32164, 57752, 20189, 34373, 35485, 34708,
       30110, 50091, 47710, 35322, 21607, 32948, 58908, 40046, 22709,
       51097, 40274, 57306, 36386, 58855, 59192, 34287, 32628, 50045,
       53818, 35317, 47136, 27886, 52672, 43665, 31208, 36830, 37707,
       44509, 28597, 47278, 27735, 55023, 33763, 48449, 33864, 47071,
       33765])

In [59]:
np.random.randint(20,40,20)

array([21, 38, 22, 37, 21, 27, 27, 24, 21, 20, 30, 29, 22, 22, 22, 29, 39,
       29, 25, 37])

In [60]:
# if we have array present in memory
# & we need to create a new array with same structure
x = np.random.random((4,6))
x

array([[0.91861647, 0.21872254, 0.40586363, 0.05619758, 0.32952703,
        0.11154013],
       [0.14537699, 0.08489182, 0.45739272, 0.31240418, 0.56601513,
        0.28734958],
       [0.1362094 , 0.04311114, 0.67260435, 0.24655134, 0.90626956,
        0.68296169],
       [0.19725782, 0.82689276, 0.86896956, 0.55788217, 0.29889393,
        0.06772117]])

In [61]:
x.shape

(4, 6)

In [62]:
# create an array of 1's with same shape as that of x
np.ones_like(x)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [64]:
np.ones_like(x,dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [67]:
r=np.random.random((6,7))
r

array([[0.69382717, 0.08302273, 0.74386764, 0.56758893, 0.26160994,
        0.2122715 , 0.55307299],
       [0.67816765, 0.9075087 , 0.31445265, 0.87184197, 0.42692714,
        0.37849889, 0.73939134],
       [0.38691255, 0.56776466, 0.15660074, 0.19675817, 0.80976415,
        0.80092468, 0.73196135],
       [0.23686679, 0.45689256, 0.60883757, 0.33983566, 0.07145428,
        0.86316874, 0.16805653],
       [0.39837245, 0.2602181 , 0.78385985, 0.13921865, 0.54607594,
        0.03069564, 0.48854944],
       [0.55459117, 0.08711964, 0.02938127, 0.08684425, 0.59564059,
        0.62890082, 0.8194051 ]])

In [68]:
r.shape

(6, 7)

In [69]:
np.ones_like(r)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [70]:
np.ones_like(r,dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [71]:
np.empty_like(r)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [72]:
np.empty_like(r,dtype=int)

array([[4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 5832796],
       [6750325, 7209057, 6815844, 7471201, 6357066, 7602279, 7340129],
       [3014748, 7340137, 7602297, 7274600, 6029422, 7471216, 6684783],
       [7077993, 6226021, 6619236, 6357094, 7078005, 6029428, 6881384],
       [7602291, 7471215, 3014777, 7405683, 6881388, 6619252, 6946861],
       [7667823, 7209074, 7077985, 7340032,     121,       0,       0]])

In [73]:
np.zeros_like(r)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [74]:
np.zeros_like(r,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [75]:
np.empty_like(r)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [76]:
np.ones_like(r)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [77]:
np.empty_like(r,dtype=int)

array([[4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 5832796],
       [6750325, 7209057, 6815844, 7471201, 6357066, 7602279, 7340129],
       [3014748, 7340137, 7602297, 7274600, 6029422, 7471216, 6684783],
       [7077993, 6226021, 6619236, 6357094, 7078005, 6029428, 6881384],
       [7602291, 7471215, 3014777, 7405683, 6881388, 6619252, 6946861],
       [7667823, 7209074, 7077985, 7340032,     121, 8205364,     100]])

In [78]:
np.empty_like(r)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [79]:
np.empty_like(r)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [81]:
np.zeros_like(r,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [83]:
np.empty_like(r,dtype=int)

array([[4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 5832796],
       [6750325, 7209057, 6815844, 7471201, 6357066, 7602279, 7340129],
       [3014748, 7340137, 7602297, 7274600, 6029422, 7471216, 6684783],
       [7077993, 6226021, 6619236, 6357094, 7078005, 6029428, 6881384],
       [7602291, 7471215, 3014777, 7405683, 6881388, 6619252, 6946861],
       [7667823, 7209074, 7077985, 7340032,     121,       0,       0]])

# Typecasting in numpy

In [84]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [85]:
np.arange(20).dtype

dtype('int32')

In [88]:
np.arange(20,dtype=float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])