In [1]:
import numpy as np

In [2]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [3]:
np.arange(1,25).reshape(4,6) # row major

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [4]:
np.arange(1,25).reshape(4,6,order='f') # Column major

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

In [5]:
np.info('reshape')

     *** Found in numpy ***
 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' optio

In [6]:
np.arange(1,25).reshape(4,6,order='C') 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [7]:
np.arange(1,25).reshape(4,6,order='A') #without chnging data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [8]:
a = np.arange(1,25).reshape(4,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [10]:
b=np.arange(1,25)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
b.reshape(6,4,order='f')

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [12]:
b.reshape(6,4,order='C')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [13]:
b       # b is unchanged

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
b = b.reshape(6,4,order='F')
b

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

# Conditional based selection

In [15]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [16]:
#fetch values >10
a > 10 
#performs elementwise operation
#it give u an array of boolean output 

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [17]:
#boolean indexing is supported
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
# Concept of Boolean indexing
# total 4 rows present in a
# indexing works on rows: and we are supplying boolean index
a[ [True,False,True,False] ]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [19]:
a[ [False,False,True,False] ]

array([[13, 14, 15, 16, 17, 18]])

In [20]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [21]:
# more than one condition we want to test
#fetch values divisible by 5 and 7
a % 5 == 0

array([[False, False, False, False,  True, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False]])

In [22]:
a % 7 ==0

array([[False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False]])

In [23]:
#Logical: and or not
# bitwise: &(and) |(or) ~(not) ^(XOR)
(a % 5==0) | (a % 7 ==0)

array([[False, False, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False,  True,  True, False, False, False]])

In [24]:
#fetch values divisible by 5 and 10
a[(a%5 ==0) & (a%10 == 0)]


array([10, 20])

In [25]:
a[(a%5==0 | (a%7==0))]

array([ 5, 10, 15, 20, 21])

In [26]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [27]:
a>18

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True]])

In [28]:
a[a>18]

array([19, 20, 21, 22, 23, 24])

# Can we compare 2 arrays?

In [29]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [30]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [31]:
x<y

array([[ True,  True],
       [ True,  True]])

In [32]:
x>y

array([[False, False],
       [False, False]])

In [33]:
x[x<y]

array([1, 2, 3, 4])

In [34]:
y[x<y]

array([5, 6, 7, 8])

In [35]:
x[x>y]

array([], dtype=int32)

In [36]:
y[x>y]

array([], dtype=int32)

# Scalar mathematics over numpy array

In [37]:
x

array([[1, 2],
       [3, 4]])

In [38]:
#add 10 in each element
x+10
#output is temp.

array([[11, 12],
       [13, 14]])

In [39]:
x

array([[1, 2],
       [3, 4]])

In [41]:
# for permant result use asignment operator
x+=10
x
#changes persist in x , inplace operation

array([[21, 22],
       [23, 24]])

In [42]:
x

array([[21, 22],
       [23, 24]])

In [43]:
y

array([[5, 6],
       [7, 8]])

In [45]:
y+=10
y

array([[25, 26],
       [27, 28]])

In [46]:
y

array([[25, 26],
       [27, 28]])

In [47]:
z=np.array([[6,7],[3,5]])
z

array([[6, 7],
       [3, 5]])

In [48]:
z + 10

array([[16, 17],
       [13, 15]])

In [49]:
z

array([[6, 7],
       [3, 5]])

In [51]:
z+=10
z

array([[26, 27],
       [23, 25]])

In [52]:
z

array([[26, 27],
       [23, 25]])

In [53]:
z+10

array([[36, 37],
       [33, 35]])

In [54]:
z

array([[26, 27],
       [23, 25]])

In [55]:
z+=10
z

array([[36, 37],
       [33, 35]])

In [56]:
#Using np.add 10
np.add(x,10)
#output is temp.

array([[31, 32],
       [33, 34]])

In [57]:
x

array([[21, 22],
       [23, 24]])

In [58]:
# if u want to do the addition of x , y [ vector addition]
display(x,y)
x + y

array([[21, 22],
       [23, 24]])

array([[25, 26],
       [27, 28]])

array([[46, 48],
       [50, 52]])

In [59]:
x

array([[21, 22],
       [23, 24]])

In [60]:
y

array([[25, 26],
       [27, 28]])

In [61]:
np.add(x,y)

array([[46, 48],
       [50, 52]])

In [62]:
#Use np.subtract()
np.subtract(x,10)# output is temp.

array([[11, 12],
       [13, 14]])

In [63]:
x

array([[21, 22],
       [23, 24]])

In [64]:
np.substract(x,y)

AttributeError: module 'numpy' has no attribute 'substract'

In [65]:
np.divide(x,10)

array([[2.1, 2.2],
       [2.3, 2.4]])

In [67]:
np.multiply(y,10)

array([[250, 260],
       [270, 280]])

In [68]:
np.floor_divide(x,10)

array([[2, 2],
       [2, 2]], dtype=int32)

In [69]:
np.floor_divide(y,10)

array([[2, 2],
       [2, 2]], dtype=int32)

In [70]:
x

array([[21, 22],
       [23, 24]])

In [71]:
y

array([[25, 26],
       [27, 28]])

In [72]:
np.mod(x,2)

array([[1, 0],
       [1, 0]], dtype=int32)

In [73]:
np.mod(y,10)

array([[5, 6],
       [7, 8]], dtype=int32)

In [74]:
np.power(x,4)

array([[194481, 234256],
       [279841, 331776]], dtype=int32)

In [75]:
x

array([[21, 22],
       [23, 24]])

In [76]:
# We want an array 4 X 4 in whcih all values must be True
np.full((4,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
np.ones((4,4),dtype='bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [78]:
#We want an array 4 X 4 in whcih all values must be False
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [79]:
np.zeros((4,4),dtype='bool')

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [80]:
#We want an array 4 X 4 in whcih diagonal values must be True and non diagonal False
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [82]:
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [83]:
# We want an array 4 X 4 in whcih diagonal values must be False and non diagonal True
e = np.identity(4,dtype=int)
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [84]:
e2 = np.invert(e)
e2

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [85]:
e2.astype('bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [86]:
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [87]:
~ e.astype('bool')

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [88]:
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [89]:
~e

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]], dtype=int32)

In [90]:
~1

-2

In [91]:
~0

-1

In [92]:
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [93]:
e.dtype

dtype('int32')

In [94]:
e.astype(float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# np.where()
- convert values > 12 as 1 and values<12 as 0

In [95]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [96]:
# np.where(condition, return x if True , else y)
np.where(a>12,1,0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [97]:
np.where(a>12,True,False)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [98]:
# suqare value if its % 5 ==0 (divisible by 5)
np.where(a%5==0,a**2,-a)
# values divisible by 5 => square
# values not divisible by 5=> make them -ve

array([[ -1,  -2,  -3,  -4,  25,  -6],
       [ -7,  -8,  -9, 100, -11, -12],
       [-13, -14, 225, -16, -17, -18],
       [-19, 400, -21, -22, -23, -24]])

In [99]:
np.where(a%5==0,a**2,0)

array([[  0,   0,   0,   0,  25,   0],
       [  0,   0,   0, 100,   0,   0],
       [  0,   0, 225,   0,   0,   0],
       [  0, 400,   0,   0,   0,   0]], dtype=int32)

In [100]:
condition = np.array(['on','off','on','on','off'])
condition

array(['on', 'off', 'on', 'on', 'off'], dtype='<U3')

In [101]:
# Convert on as 1 and off as 0
np.where(condition=='on',1,0)

array([1, 0, 1, 1, 0])

# Splitting of array

In [102]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [103]:
#Split an array into multiple sub-arrays as views into `ary`.
np.split(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [104]:
#Split an array into multiple sub-arrays as views into `ary`.
np.split(a,3) # odd distribustion is not allowed

ValueError: array split does not result in an equal division

In [105]:
#Split an array into multiple sub-arrays as views into `ary`.
np.split(a,4)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

In [106]:
# unpacking
s1,s2,s3,s4 = np.split(a,4)

In [107]:
s1

array([[1, 2, 3, 4, 5, 6]])

In [108]:
s3

array([[13, 14, 15, 16, 17, 18]])

In [109]:
s4

array([[19, 20, 21, 22, 23, 24]])

## columnwise split

In [111]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [112]:
np.split(a,2,axis=1)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [114]:
np.split(a,3,axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [115]:
a.shape

(4, 6)

In [117]:
np.vsplit(a,2) # spliting by rows

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [119]:
np.hsplit(a,3) #spliting by columns

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

# np.append()
- axis = 1 [for Column]
- axis = 0 [for row]
- axis= None [for 1D array]

In [120]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [121]:
a.ndim

2

In [122]:
#Append values to the end of an array.
# When we have axis=None it will conver n-D array to 1D & add new element's at the end of it
np.append(a,100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 100])

In [123]:
np.append(a,range(101,106))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24, 101, 102,
       103, 104, 105])

In [124]:
np.append(a,range(10,20))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [125]:
# append values  in row
np.append(a,[[-1],[-2],[-3],[-4]],axis=1)

array([[ 1,  2,  3,  4,  5,  6, -1],
       [ 7,  8,  9, 10, 11, 12, -2],
       [13, 14, 15, 16, 17, 18, -3],
       [19, 20, 21, 22, 23, 24, -4]])

In [126]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [127]:
#append value in column
# PS: append a row of zero's
np.append(a,[[0,0,0,0,0,0]],axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0,  0]])

In [135]:
np.append(a,[[1],[2],[3],[4]],axis=1)

array([[ 1,  2,  3,  4,  5,  6,  1],
       [ 7,  8,  9, 10, 11, 12,  2],
       [13, 14, 15, 16, 17, 18,  3],
       [19, 20, 21, 22, 23, 24,  4]])

In [136]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [137]:
# can we add multiple rows: No
np.append(a,[[0,0,0,0,0,0]],[[2,2,2,2,2,2]],axis=0)

TypeError: _append_dispatcher() got multiple values for argument 'axis'

In [138]:
np.append(a,[[0,0,0,0,0,0],[2,2,2,2,2,2]],axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0,  0],
       [ 2,  2,  2,  2,  2,  2]])

# np.delet

In [139]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [140]:
a[-1]

array([19, 20, 21, 22, 23, 24])

In [141]:
"""
Signature: np.delete(arr, obj/index, axis=None)
Docstring:
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
"""
# this will remove last element bcz axis=None
np.delete(a,-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [142]:
# delete last row
np.delete(a,-1,axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [143]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [144]:
# delete a last column, but temp.
np.delete(a,-1,axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [145]:
a # original array is unchanged

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [146]:
# delete a column at index 2,3
np.delete(a,[2,3],axis=1)

array([[ 1,  2,  5,  6],
       [ 7,  8, 11, 12],
       [13, 14, 17, 18],
       [19, 20, 23, 24]])

In [147]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [148]:
# remove 2
np.delete(a,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [149]:
# delete odd numbers from array a
np.delete(a,range(0,24,2))

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [150]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [151]:
list(range(0,24,2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]

# Convert nD to 1D

In [152]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [153]:
a.ndim

2

In [154]:
a.size

24

In [155]:
a.shape

(4, 6)

In [156]:
#reshape
a.reshape(24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [157]:
# ravel:Return a flattened array.
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [158]:
np.ravel(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [159]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])