In [22]:
import numpy as np

In [23]:
print(dir())

['In', 'Out', '_', '_18', '_4', '_5', '_6', '_7', '_8', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', '_i17', '_i18', '_i19', '_i2', '_i20', '_i21', '_i22', '_i23', '_i3', '_i4', '_i5', '_i6', '_i7', '_i8', '_i9', '_ih', '_ii', '_iii', '_oh', 'array', 'exit', 'get_ipython', 'np', 'quit']


In [24]:
# I want 4x4 numpy array whose all value set to True
np.full((4,4),fill_value=True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
# I want 4x4 numpy array whose all value set to False
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
# I want 4x4 numpy array whose diagonal value set to True and non diagonal False
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [28]:
#Assignment: I want 4x4 numpy array whose diagonal value set to False and non diagonal True
np.full((4,4),fill_value=False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
e = np.ones((4,4),dtype=bool)
np.fill_diagonal(e,False)

In [31]:
e

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [32]:
# another solution
~ np.identity(4,bool)

# ~ tild sign: used for bitwise not operatioon
# means if True then convert to False
#  & if False then convert to True

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [33]:
not True # logical not (works on single input) , ~ bitwise not(works on multiple inputs)

False

# Check different properties of numpy array


In [34]:
a=np.random.random((4,4))

In [35]:
a

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037],
       [0.72697742, 0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417],
       [0.24222459, 0.76527028, 0.02939472, 0.81108784]])

In [36]:
# size: total elements present
a.size

16

In [37]:
# check shape
a.shape

(4, 4)

In [38]:
print('Total number of rows',a.shape[0])
print('Total number of columns',a.shape[1])

Total number of rows 4
Total number of columns 4


In [39]:
# a memory in bytes to each element
a.itemsize

8

In [40]:
# check data type
a.dtype

dtype('float64')

In [41]:
# check a memory
a.data

In [42]:
#check dimension
a.ndim

2

# Shape manipulation

In [43]:
print(a)
print(a)
print('Ganesh')

[[0.66266789 0.38666235 0.88074993 0.81624037]
 [0.72697742 0.48106905 0.72694264 0.83866852]
 [0.23253555 0.99409775 0.51183877 0.84741417]
 [0.24222459 0.76527028 0.02939472 0.81108784]]
[[0.66266789 0.38666235 0.88074993 0.81624037]
 [0.72697742 0.48106905 0.72694264 0.83866852]
 [0.23253555 0.99409775 0.51183877 0.84741417]
 [0.24222459 0.76527028 0.02939472 0.81108784]]
Ganesh


In [45]:
display(a,a,'Ganesh')

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037],
       [0.72697742, 0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417],
       [0.24222459, 0.76527028, 0.02939472, 0.81108784]])

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037],
       [0.72697742, 0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417],
       [0.24222459, 0.76527028, 0.02939472, 0.81108784]])

'Ganesh'

In [46]:
#shape
a.shape

(4, 4)

In [47]:
# 16 eleements: 
# 1,16
# 2,8
# 8,2
# 4,4
# 16,1
#---- 3D
"""
1,4,4
2,2,4
4,2,2
"""

'\n1,4,4\n2,2,4\n4,2,2\n'

# reshape():it changes shape temp.


In [48]:
b=np.array((4,4))

In [49]:
b

array([4, 4])

In [50]:
# convert shape to 8(rows)x2(columns)
a.reshape(8,2)

array([[0.66266789, 0.38666235],
       [0.88074993, 0.81624037],
       [0.72697742, 0.48106905],
       [0.72694264, 0.83866852],
       [0.23253555, 0.99409775],
       [0.51183877, 0.84741417],
       [0.24222459, 0.76527028],
       [0.02939472, 0.81108784]])

In [51]:
#3D using reshape
# 2x4x2
a.reshape(2,4,2)

array([[[0.66266789, 0.38666235],
        [0.88074993, 0.81624037],
        [0.72697742, 0.48106905],
        [0.72694264, 0.83866852]],

       [[0.23253555, 0.99409775],
        [0.51183877, 0.84741417],
        [0.24222459, 0.76527028],
        [0.02939472, 0.81108784]]])

In [53]:
a.reshape(4,2,2)

array([[[0.66266789, 0.38666235],
        [0.88074993, 0.81624037]],

       [[0.72697742, 0.48106905],
        [0.72694264, 0.83866852]],

       [[0.23253555, 0.99409775],
        [0.51183877, 0.84741417]],

       [[0.24222459, 0.76527028],
        [0.02939472, 0.81108784]]])

In [54]:
a # a is unchanged

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037],
       [0.72697742, 0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417],
       [0.24222459, 0.76527028, 0.02939472, 0.81108784]])

# resize(): to do changes permanently

In [55]:
a

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037],
       [0.72697742, 0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417],
       [0.24222459, 0.76527028, 0.02939472, 0.81108784]])

In [56]:
a.shape

(4, 4)

In [57]:
#convert into 1D permenantly
a.resize(16)

In [58]:
a

array([0.66266789, 0.38666235, 0.88074993, 0.81624037, 0.72697742,
       0.48106905, 0.72694264, 0.83866852, 0.23253555, 0.99409775,
       0.51183877, 0.84741417, 0.24222459, 0.76527028, 0.02939472,
       0.81108784])

In [59]:
a.ndim

1

In [60]:
a.shape

(16,)

In [61]:
# lets change to 2D
a.resize((4,4))

In [62]:
a

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037],
       [0.72697742, 0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417],
       [0.24222459, 0.76527028, 0.02939472, 0.81108784]])

In [63]:
a.shape

(4, 4)

In [64]:
#Lets change to 3D
a.resize(4,2,2)

In [65]:
a

array([[[0.66266789, 0.38666235],
        [0.88074993, 0.81624037]],

       [[0.72697742, 0.48106905],
        [0.72694264, 0.83866852]],

       [[0.23253555, 0.99409775],
        [0.51183877, 0.84741417]],

       [[0.24222459, 0.76527028],
        [0.02939472, 0.81108784]]])

In [66]:
a.ndim

3

In [67]:
a.shape

(4, 2, 2)

In [68]:
a.shape=(2,8)

In [69]:
a

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037, 0.72697742,
        0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417, 0.24222459,
        0.76527028, 0.02939472, 0.81108784]])

In [70]:
a.shape

(2, 8)

In [71]:
a.size

16

In [72]:
x=np.array([1,2,3,4,5])

In [73]:
x

array([1, 2, 3, 4, 5])

In [74]:
x.dtype

dtype('int32')

In [75]:
x.__sizeof__()

124

In [77]:
y=np.array([1,2,3,4,5],dtype=object)
y

array([1, 2, 3, 4, 5], dtype=object)

In [78]:
y.__sizeof__()

144

# transpose: convert row to column and viceversa

In [79]:
a

array([[0.66266789, 0.38666235, 0.88074993, 0.81624037, 0.72697742,
        0.48106905, 0.72694264, 0.83866852],
       [0.23253555, 0.99409775, 0.51183877, 0.84741417, 0.24222459,
        0.76527028, 0.02939472, 0.81108784]])

In [80]:
a.shape

(2, 8)

In [81]:
a.transpose()   #changes are temp.

array([[0.66266789, 0.23253555],
       [0.38666235, 0.99409775],
       [0.88074993, 0.51183877],
       [0.81624037, 0.84741417],
       [0.72697742, 0.24222459],
       [0.48106905, 0.76527028],
       [0.72694264, 0.02939472],
       [0.83866852, 0.81108784]])

In [82]:
a.T

array([[0.66266789, 0.23253555],
       [0.38666235, 0.99409775],
       [0.88074993, 0.51183877],
       [0.81624037, 0.84741417],
       [0.72697742, 0.24222459],
       [0.48106905, 0.76527028],
       [0.72694264, 0.02939472],
       [0.83866852, 0.81108784]])

In [83]:
np.transpose(a)

array([[0.66266789, 0.23253555],
       [0.38666235, 0.99409775],
       [0.88074993, 0.51183877],
       [0.81624037, 0.84741417],
       [0.72697742, 0.24222459],
       [0.48106905, 0.76527028],
       [0.72694264, 0.02939472],
       [0.83866852, 0.81108784]])

# Indexing over numpy

In [85]:
b=np.arange(1,25).reshape(6,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [1]:
# [[ 1,  2,  3,  4],[ 5,  6,  7,  8],[ 9, 10, 11, 12],[13, 14, 15, 16],[17, 18, 19, 20],[21, 22, 23, 24]]

In [87]:
# indexing in numpy works on rows
b[0]

array([1, 2, 3, 4])

In [89]:
b[4]

array([17, 18, 19, 20])

In [90]:
#access 11
b[2]

array([ 9, 10, 11, 12])

In [91]:
b[2,2]

11

In [92]:
#acess 20
b[4,3]

20

In [93]:
#access 6
b[1,1]

6

In [97]:
#acess 21
b[5,0]

21

In [98]:
c=b.reshape(3,4,2)

In [99]:
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [100]:
#acess 18
c[2,0,1]

18

In [102]:
#acess 19
c[2,1,0]

19

In [103]:
#acess 15
c[1,3,0]

15

In [104]:
# is _ve indexing is posible???
c[-2]

array([[ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [105]:
c[-3] #-ve indexing is allowed

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# slicing

In [106]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [107]:
#slicing works on rows first
b[:] #[start:Stop] row

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [108]:
#last 4 rows
b[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [109]:
"""
[ 9, 10, 11, 12],
[13, 14, 15, 16],
"""
b[2:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [112]:
"""
[ 1,  2,  3,  4]
[ 9, 10, 11, 12]
[17, 18, 19, 20]
"""
b[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [113]:
#access first and last row
b[::5]

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])

In [114]:
# row 13 and 21
# Rule: If we want to skip one(n) row then step by 2(n+1)
b[3::2]

array([[13, 14, 15, 16],
       [21, 22, 23, 24]])

In [116]:
# row 21 13 5
b[-1::-2]

array([[21, 22, 23, 24],
       [13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [117]:
# b[start:stop]
# b[start_index:stop_index:step]
#b[::,::] {row,column}

In [118]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [119]:
"""
10,11
14,15
"""
b[2:4,1:3]


array([[10, 11],
       [14, 15]])

In [120]:
"""
[ 1,  2]
[5,  6]
"""
b[:2,:2]

array([[1, 2],
       [5, 6]])

In [123]:
# 7,  8
# 19, 20
b[1::3,2:]

array([[ 7,  8],
       [19, 20]])

In [124]:
b[::-1]

array([[21, 22, 23, 24],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [125]:
#access last column starting with  4
b[:,-1:]

array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])

In [126]:
#access last column starting with  4
b[:,3:]

array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])

In [127]:
#fetch corner elements
# 1,4,21,24
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [128]:
#check shape
b.shape

(6, 4)

In [129]:
b[::5,::3]

array([[ 1,  4],
       [21, 24]])

In [130]:
# 19,20
# 23,24
b[4:,2:]

array([[19, 20],
       [23, 24]])

In [132]:
#access middle 2 columns
b[::,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [133]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [134]:
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8],
[13, 14, 15, 16],
[21, 22, 23, 24]]

[[1, 2, 3, 4], [5, 6, 7, 8], [13, 14, 15, 16], [21, 22, 23, 24]]

In [140]:
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8],
[13, 14, 15, 16],
[21, 22, 23, 24]]
b[[0,1,3,5]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [21, 22, 23, 24]])

In [144]:
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8]]
b[[0,1]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [145]:
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8]]
b[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
[[ 1,  2,  3,  4],
[ 5,  6,  7,  8]]
b[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])